### ISSUE TITLE
Feature Request:  Specify number of columns

### ISSUE THREAD

**Issue by TeleTwanger** [conceptualspace/yet-another-speed-dial#10]
Thanks for your good work...

**Comment by xan2622** [comment]
I second this request. 

I hope that the addon will feature columns.

**Comment by conceptualspace** [comment]
sure. do you mean keeping the dials a fixed size, and limiting the number per row? or do you mean to fill the screen with the defined number of columns (dials will grow or shrink)?

**Comment by xan2622** [comment]
Second option sounds more complicated to code so, in the meantime, "keeping the dials at a fixed size" seems more reasonable. 

By "columns", I think that @TeleTwanger meant something like this : 

![firefox-add-more-top-sites-rows-1](https://user-images.githubusercontent.com/1732773/79193914-daeed480-7e2b-11ea-9846-4d348f9cd167.jpg)

https://www.ghacks.net/2018/05/17/how-to-add-more-top-sites-rows-to-firefox/

What we want is to add more thumbnails (similar to this image), so it's in fact being able to add more "**rows**" (not "columns").

**Comment by TeleTwanger** [comment]
Use the specified number of columns, and maybe allow the sizing of the dials.

**Comment by bunnyroo** [comment]
I'd like to see this as well. I think the way I've seen this work on other browsers/speed dials is that you set the number of columns and you set the size of your thumbnails (small, medium, large). No need to dynamically adjust the size of the thumbnails. They would all be one set size in the set columns.

**Comment by conceptualspace** [comment]
ok, slated for v1.7

**Comment by conceptualspace** [comment]
resolved in 465d287
