### ISSUE TITLE
Feature request: Pull favicons to use as image

### ISSUE THREAD

**Issue by doug-harvey** [conceptualspace/yet-another-speed-dial#105]
As title really. Would be great especially bookmarking a lot of Google workspace pages the icons all end up the same. For a lot of websites the favicon is a lot more relevant than the auto discovered image.

**Comment by conceptualspace** [comment]
it does pull the favicon if the site has one. if you edit a dial you should be able to scroll through the images it found for the site. usually the favicons are not very big so yasd typically shows the open graph image by default
