### ISSUE TITLE
Can't edit URLs (and a suggestion to let the user add a title)

### ISSUE THREAD

**Issue by xan2622** [conceptualspace/yet-another-speed-dial#11]
When you click on **+** to add a new thumbnail, the user is invited to enter an address: 

![Annotation 2020-04-13 143917](https://user-images.githubusercontent.com/1732773/79121063-b562bc00-7d94-11ea-9ac2-f1461daa9fe4.jpg)

Then, the addon opens a new tab (with the given URL) to capture an image (for the thumbnail):

![Annotation 2020-04-13 143802](https://user-images.githubusercontent.com/1732773/79121151-ecd16880-7d94-11ea-9bf2-b0aec733aa83.jpg)

But as you notice, the label below the thumbnail shows the URL address.

And if you right-click on the thumbnail (to edit it), you can notice that the address is in the title field, and the address field is empty (and greyed). There's no way to edit the address: 

![Annotation 2020-04-13 143820](https://user-images.githubusercontent.com/1732773/79121278-3621b800-7d95-11ea-94a3-5541327e1f74.jpg)

Suggestion: 
Please add a Title field on the dialog that appears when the user clicks on **+**.

This way, the user would be able to enter an address (mandatory, of course) and a custom title if he/she wants to. If no title is provided by the user, then the addon would just copy the URL to the title field.

**Comment by conceptualspace** [comment]
going to do this in v1.7
