### ISSUE TITLE
[Feature Request] Choose folder to use as Speed Dial

### ISSUE THREAD

**Issue by Darthagnon** [conceptualspace/yet-another-speed-dial#12]
Currently, by trial and error, I realised that Yet Another Speed Dial was using ```Other Favourites/Other/Archives/Vivaldi Default/Speed Dial``` as the Speed Dial folder. I would prefer to choose which folder to use on the Speed Dial (e.g. ```Other Favourites/Speed Dial```)

Any chance the option to choose the bookmarks folder to use for the Speed Dial could be implemented?

As a side note, I noticed unusually high CPU usage from the Yet Another Speed Dial extension process whenever I had a Speed Dial page open. I'm using Edgium Version 84.0.508.0 (Official build) dev (64-bit)

**Comment by conceptualspace** [comment]
if you go into the bookmarks manager you can move the speed dial folder wherever you want. as long as you dont rename it yasd should find it :)
