### ISSUE TITLE
Backward compatibility?

### ISSUE THREAD

**Issue by ObiSandwich** [conceptualspace/yet-another-speed-dial#14]
Love this addon, slick and much better than the rest :) Just one thing that is stopping me from using it - because the Firefox Addon page says my browser is too old, do you offer either a compatible version or an older Firefox .xpi download please? 

I use Firefox type browsers: Basilisk and Pale Moon.

Thanks,

**Comment by conceptualspace** [comment]
thanks! i'd have to check but i think it's just the toolbar button that requires v59+. so i'll try publishing a version targeting v55 for you and hopefully everything else works :)

**Comment by conceptualspace** [comment]
here u go!

https://conceptualspace.net/yasd-v1.6.8-ff55.xpi

**Comment by ObiSandwich** [comment]
Thanks so much. But now I get a message from both browsers that says "Does not support web extensions". Which is weird because I've installed .xpi addons before on these browsers eg. Decentraleyes, Speed Dial FVD, uBlock etc.

**Comment by conceptualspace** [comment]
looking at it a little closer i think palemoon expects an XUL extension which is a different than what YASD is written in. unfortunately i think achieving backwards compatibility to that extent would require some development effort, not just removing the minimum required version string from the manifest as i did with the XPI above. sorry man. i would suggest trying brave browser!

**Comment by ObiSandwich** [comment]
No worries, thanks for the suggestion. I'll take a look at Vivaldi. 

I've got your app working on some of my other machines, keep up the good work.
