### ISSUE TITLE
Thumbnails not saving (Ubuntu)

### ISSUE THREAD

**Issue by Pioden** [conceptualspace/yet-another-speed-dial#16]
I use **yet another speed dial** on all my PC's - and it's really good. Just one thing, the thumbnails don't seem to save on Linux. On Linux I added thumbnails JPEGs for all my Dials, and saved them as I added them. I open a new tab, and they're gone - no thumbnail pictures :-(

Saving thumbnails works on my iMac (Catalina with latest Firefox), but not on my Linux machines (Ubuntu 20.04 with latest Firefox).

**Comment by conceptualspace** [comment]
Thanks for the report. That's odd, I use Debian myself so I don't think it's anything intrinsic to Linux. If you go to the extensions page in your browser (ex. chrome://extensions) do you see any error messages on YASD? Could you share one of the images you're trying? If you
