### ISSUE TITLE
Feature Request: (re-)capture website image with delay

### ISSUE THREAD

**Issue by lostping** [conceptualspace/yet-another-speed-dial#17]
There are quite some pages out there with landing page effects. Then you might get a blank website image.
It would be awesome to have an option to re-capture the website image (with delay in n seconds option).

Awesome addon, btw.

**Comment by conceptualspace** [comment]
v1.9 adds a menu item to refresh the site thumbnails :)

instead of adding a delay to the capture process, you can just add the speed dial from the page after it's loaded using the context menu or the toolbar button. cheers
