### ISSUE TITLE
Shrink extension name in address bar?

### ISSUE THREAD

**Issue by DaveWalk1** [conceptualspace/yet-another-speed-dial#2]
Hello!
This may be a small thing, but the extension name takes up a chunk of the address bar on every new tab. Is there a way to hide this or make it less obtrusive?

I often open a new tab and type into the address bar. The starting position for text is shifted over a bit.

Your extension: 
![image](https://user-images.githubusercontent.com/25713392/60756587-0b682f00-9fcd-11e9-9334-df548e15dda3.png)

Regular bar: 
![image](https://user-images.githubusercontent.com/25713392/60756616-6d289900-9fcd-11e9-9bde-3e4974b24f24.png)

**Comment by DaveWalk1** [comment]
Image from a normal speed dial: ![image](https://user-images.githubusercontent.com/25713392/60756653-035cbf00-9fce-11e9-897d-5cc6468430cd.png)

**Comment by conceptualspace** [comment]
that is set by the browser and unfortunately i dont think it can be modified. (if you know of any extensions that are able to customize the home or new tab pages without that there, please let me know!)

also, typically the address bar should be in focus so you can just start typing a URL and not have to click it at all. but there seems to be a bug in firefox where this does not always occur:

https://bugzilla.mozilla.org/show_bug.cgi?id=1563254

if you are experiencing that issue too please feel free to comment on or upvote the bug above.

thanks!
