### ISSUE TITLE
Feature request: use page title as title for the dial

### ISSUE THREAD

**Issue by Cris70** [conceptualspace/yet-another-speed-dial#20]
Presently the URL is used as title for the dial. Why not use the page title instead?
Other speed dial add-ons use this and it looks nice.
BTW thank you for your work, this add-on is awesome.

**Comment by conceptualspace** [comment]
nice catch. it does use the title if you add via the toolbar button, but wasn't fetching the title explicitly when adding via the speed dial page. i'll try to add to v1.8

**Comment by Cris70** [comment]
Great! Thanks

**Comment by conceptualspace** [comment]
done in 85c00e8b7f9c63c2c75c7ef9eb5bcc065323bb14
