### ISSUE TITLE
Bug: sometimes dial title is not saved

### ISSUE THREAD

**Issue by Cris70** [conceptualspace/yet-another-speed-dial#21]
I still have not found a way to always reproduce it, however sometimes a dial won't keep its new title after I edit it.
Initially it seems that the new title sticks, but if I close the speed dial page and the re-open it, the customized title is gone and the url is back. This happens even after editing and saving several times.

**Comment by conceptualspace** [comment]
should be fixed in v1.8 -- there were some race conditions when either of the following were true: you changed the title and thumbnail at the same time, or if you had more than one dial with the same url (for example in a different folder). thanks for the report!
