### ISSUE TITLE
Brave Bookmarks Folder Bug?

### ISSUE THREAD

**Issue by heywolf15** [conceptualspace/yet-another-speed-dial#25]
I'm start clean installation of brave and first thing I did was importing bookmarks from firefox.
The speed dial bookmarks from firefox is in a different folder, not in "other bookmarks".
Installing "yet another speed dial" and its doesn't create speed dial folder in other bookmarks.
I thought it's because it doesn't have bookmark yet, but after clicking any websites to speed dial with right click or toolbar button.

The speed dials tab still empty, no speed dial folder.
Using the button on speed dial tab, its save the site and capture the image, but I can't find the folder or the site on any bookmarks folder. 
The same with add folder on speed dial tab and add any site there.
When I click bookmarks this tab, I can choose the newly added folder that I create on speed dial tab.
Still can't find it on the bookmark manager, the folder and the site.

I fix this with deleting all the exported bookmarks, so it's all the bookmarks.
Re-installing yet another speed dial
Testing again, it works normally and create a speed dial folder.
Then importing the bookmarks.

**Comment by conceptualspace** [comment]
thanks for the report. i'll try to replicate

**Comment by conceptualspace** [comment]
should be fixed in v1.15.6
