### ISSUE TITLE
Unable to delete bookmarks to service pages

### ISSUE THREAD

**Issue by thebndr** [conceptualspace/yet-another-speed-dial#26]
I've added a few Firefox service pages to my bookmarks.
When I try to edit them, the changes are not saved. And when I try to delete it, nothing happens.

about:newtab
about:preferences#home

**Comment by conceptualspace** [comment]
thanks, will be patched in next release. a couple of other handy ones for firefox:

chrome://browser/content/places/places.xhtml
chrome://browser/content/places/historySidebar.xhtml

**Comment by thebndr** [comment]
Perhaps it is necessary to restrict the addition of these addresses to bookmarks?

**Comment by conceptualspace** [comment]
it seems `about:` and `chrome:` URL schemes are not allowed in web extensions, even when explicitly defined in the manifest :/

https://developer.chrome.com/docs/extensions/mv2/match_patterns/

presently im not sure how to work around this.. open to suggestions
