### ISSUE TITLE
Some points of improvement

### ISSUE THREAD

**Issue by Myghalloween** [conceptualspace/yet-another-speed-dial#28]
- Choice for a 24 hour clock format.
- Possibility to choose a format of square thumbnails for big icons.
- Choice for launch in a new tab or not.
- a link in the settings for donations.

Great plugin. Very good work !

**Comment by conceptualspace** [comment]
thanks for the suggestions @Myghalloween  :)

 - 24h clock added to v1.14.1
 - opening in a new tab is a right-click context menu option
 - resizing is being tracked in #22 
 - a donation is a very nice gesture! :heart:  i've setup a github sponsors profile here: https://github.com/sponsors/conceptualspace
