### ISSUE TITLE
Cannot delete or modify "about:" links in Firefox

### ISSUE THREAD

**Issue by FMMT666** [conceptualspace/yet-another-speed-dial#29]
I accidentally created a couple of dials with "about:config", "about:profiles", etc.
Unfortunately it's not possible to delete, modify or do anything else with them.

**Comment by conceptualspace** [comment]
Temporary solution is to edit/remove them in the bookmarks manager

**Comment by FMMT666** [comment]
Lol, ok; thanks!
Never noticed that the links appear in there.
