### ISSUE TITLE
Limited # of tabs?

### ISSUE THREAD

**Issue by stcynic** [conceptualspace/yet-another-speed-dial#3]
Is there a limit to how many dials/tabs that can be put on the page? It took 12 and then suddenly stopped allowing new ones.

**Comment by conceptualspace** [comment]
there is no limit (i have just over 20 in my own case)

can you confirm the sites exist inside your bookmarks manager? they should be in the 'Other Bookmarks' > 'Speed Dial' folder.

obvious question, but are you able to scroll the page? does resizing the window (smaller or larger) have any effect?

if that doesn't help, please send me a screenshot and let me know what operating system and version of firefox you are running.
