### ISSUE TITLE
Feature request: export and import settings.

### ISSUE THREAD

**Issue by racofer** [conceptualspace/yet-another-speed-dial#31]
Unless I've not found it, it would be very very helpful to be able to export/import the current settings.

**Comment by SerafDosSantos** [comment]
I "used" SpeedDial2.com for too long... This right here is GOLD for someone like me. Importing from Speed Dial 2 exports would have been easy, but the secret is it's all in the Bookmarks Manager.

**Comment by conceptualspace** [comment]
what would you guys prefer first? import/export of YASD's own settings, or import from other extensions like speed dial 2?

both are working in beta, im just thinking about how to integrate them into the menu so it doesnt get too messy :smiley:

**Comment by racofer** [comment]
> import/export of YASD's own settings, or import from other extensions like speed dial 2?

Importing/exporting YASD's own settings would be my pick simply because it's what I would use the most, as I run YASD on multiple browsers.

**Comment by SerafDosSantos** [comment]
@conceptualspace I don't see why importing/exporting settings would be necessary if the only thing you got to do is move a bunch of bookmarks in the "Speed Dial" folder. What other info would be available besides the bookmarks urls, titles, favicons and social media images? Unless you plan to include statistics into YASD also, I don't see the need. Please explain. 

> I "used" SpeedDial2.com for too long... This right here is GOLD for someone like me. Importing from Speed Dial 2 exports would have been easy, but the secret is it's all in the Bookmarks Manager.

As I said above, it's all in the Bookmarks Manager. Why more if less & simple is quite alright?

**Comment by conceptualspace** [comment]
some users want to export a file from FVD or SD2 and be able to import it into YASD easily; i'll try adding an import button to the settings menu or maybe just on the new install page
