### ISSUE TITLE
Feature request: Tabs sorting

### ISSUE THREAD

**Issue by millionart** [conceptualspace/yet-another-speed-dial#34]
Want to be able to drag and drop sorting of tabs.

**Comment by SerafDosSantos** [comment]
sort it in the Bookmarks Manager.

**Comment by conceptualspace** [comment]
thanks @SerafDosSantos! im testing drag and drop for tab sorting, it will probably show up in the next release

**Comment by SerafDosSantos** [comment]
By the way @conceptualspace, your email yet_another_speed_dial [at] conceptualspace [dot] net isn't working...

I wanted to say a BIG THANKS for this extension!

**Comment by conceptualspace** [comment]
@SerafDosSantos that email is actually just the app identifier (let me know if you saw it published anywhere other than the source code) - but I agree it can be confusing if someone comes across it. I'll make a note to update this to a GUID in a future update.

And thank you for your support! If you haven't already, please consider leaving a review on the Chrome web store. Every bit helps to keep YASD active :smiley:
