### ISSUE TITLE
Firefox sync broke the extension

### ISSUE THREAD

**Issue by heywolf15** [conceptualspace/yet-another-speed-dial#35]
Sign in to fresh firefox profile
After the sync complete with all the bookmarks, including From other Bookmarks folder
open a new tab to open the speed dial, it just shows like nothing has been added. Complete with Info "3 Ways to add speed dials"
I can't add speed dial directly or on the site tab. 
It just broke

This can be fix by uncheck bookmarks from sync after sync for the first time
install the extension then restar the browser

**Comment by conceptualspace** [comment]
thanks for the report, will try to replicate. can you confirm your setup? devices/OS/ff version?

**Comment by heywolf15** [comment]
Laptop W10 
ff 92.0

**Comment by conceptualspace** [comment]
should be fixed in v1.15.6
