### ISSUE TITLE
Feature request: Organize in groups

### ISSUE THREAD

**Issue by heywolf15** [conceptualspace/yet-another-speed-dial#4]
Groups: Create, Delete, and Edit. Keep Dials better-organized.

**Comment by conceptualspace** [comment]
thanks for the suggestion. i agree many would find this useful. will put it on the roadmap for the next major release

**Comment by heywolf15** [comment]
Is there a way to undo deleted dials?
Deleted history will be great

**Comment by heywolf15** [comment]
when I do that, the new added bookmarks gone

**Comment by Oleekae** [comment]
Thank you, it is appreciated to have a speed deal where privacy is respected. My question is to know if the last update that is in the chrome store already adds being able to create folders for categories.

**Comment by conceptualspace** [comment]
groups (folders) added in v1.6.0
