### ISSUE TITLE
Max Columns Not Working Properly(?)

### ISSUE THREAD

**Issue by GTHub23** [conceptualspace/yet-another-speed-dial#44]
Just downloaded the add-on since FVD Speed Dial is no more, and found this to be just as minimalistic and functional as I need. However, I have one niggling issue which may or may not be a bug.

In settings I can set "Max Columns" to "3-10" or "Unlimited". Setting it to "3-8" functions just fine, but if I try and set it to "9", "10", or "Unlimited" the speed dial only allows for maximum of "8" columns to be displayed. Now, this might be a bug, or it may be a limitation of my screen resolution which is set at 1920x1080; not sure if I need a screen resolution of higher than 1920x1080 to get more than "8" columns.

If that is the issue then I suppose I can live with it. If it is a bug, hopefully there's a simple(ish) fix for it.

**Comment by conceptualspace** [comment]
thanks for the report, you're exactly correct that 8 is the maximum for your resolution. that's because the setting doesn't change the size of the dials or overflow them outside the viewport. that said, i will probably allow for more dial sizes in a future version

**Comment by GTHub23** [comment]
No probs, thanks for the rapid response!
