### ISSUE TITLE
Cannot add speed dial on ubuntu 20.04 firefox v94.0

### ISSUE THREAD

**Issue by khbehrens** [conceptualspace/yet-another-speed-dial#47]
I installed yasd to my laptop ubuntu 20.04 firefox v94.0. I cannot add a site. The url does save and I am left with only the add button. Furthermore, I had to remove firefox syncing because the existing speed dials setup on my other 4 ubuntu 20.04 machines were deleted. As soon as I reinstalled yasd on the other machines, I got the url's back in speed dials, but the laptop still exhibited the same behavior.  Any suggestions to fix this problem would be greatly appreciated. Note that the other 4 machines synced the speed dials after setting up the url's on the first machine and all I had to do is add the custom icons and arrange the layout.

**Comment by conceptualspace** [comment]
there was a bug that could cause this to occur if you happened to have a bookmark named "Speed Dial"; should be resolved in the latest commit -- i'll push it to mozilla right now so you can try it (v1.15.6)

**Comment by khbehrens** [comment]
Thanks for the speedy response! I will try to test it either tomorrow or 
Saturday. I have client machine to work on and get him out of panic mode 
and I don't know how long it will take.

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   12/02/2021 14:48
Subject:        Re: [conceptualspace/yet-another-speed-dial] Cannot add 
speed dial on ubuntu 20.04 firefox v94.0 (Issue #47)



there was a bug that could cause this to occur if you happened to have a 
bookmark named "Speed Dial"; should be resolved in the latest commit -- 
i'll push it to mozilla right now so you can try it (v1.15.6)
?
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by conceptualspace** [comment]
i'm going to mark this as resolved but if the problem persists please feel free to reopen. in that case, after you replicate the issue, please include any error messages from the background process and new tab page console (of course redact any sensitive info that might appear in the log):

1. with YASD open on the new tab page, press `ctrl` + `shift` + `i` -> open the  'console' tab
2. go to the addons manager (about:addons) -> click the gear at the top right -> select 'debug addons' -> click 'inspect' in the YASD section -> open the 'console' tab.

you can email me directly if you don't want to share log output here, dev at conceptualspace dot net

**Comment by conceptualspace** [comment]
exploring this further ive found another edge case:

if you install YASD *before* enabling browser sync, the id of the root bookmarks folder used by YASD may be silently changed by firefox during sync (essentially swapping the local speed dial folder with the synced one). but that leads to a none working tab because YASD is trying to write to the original folder that no longer exists

unfortunately i cant find any way for extensions in general to listen to the browser's sync events to react to the change, so ill have to add some logic around the page that triggers a refresh wherever its noticed that the root ID is no longer valid...

in the meantime, simply restarting the browser (or restarting/reinstalling the extension) should bring everything up to date

**Comment by khbehrens** [comment]
I performed my test last night and I can confirm that v1.15.6 did fix the 
problem. 
Thank you for the fast turnaround!

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   12/03/2021 08:39
Subject:        Re: [conceptualspace/yet-another-speed-dial] Cannot add 
speed dial on ubuntu 20.04 firefox v94.0 (Issue #47)



i'm going to mark this as resolved but if the problem persists please feel 
free to reopen. in that case, after you replicate the issue, please 
include any error messages from the background process and new tab page 
console (of course redact any sensitive info that might appear in the 
log):
with YASD open on the new tab page, press ctrl + shift + i -> open the 
'console' tab
go to the addons manager (about:addons) -> click the gear at the top right 
-> select 'debug addons' -> click 'inspect' in the YASD section -> open 
the 'console' tab.
you can email me directly if you don't want to share log output here, dev 
at conceptualspace dot net
?
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
