### ISSUE TITLE
Error when trying to install on Microsoft Edge

### ISSUE THREAD

**Issue by bb10** [conceptualspace/yet-another-speed-dial#48]
Hi

First of all, excellent extension. It's exactly what I've been looking for.

Unfortunately there seems to be a problem on the Microsoft Edge browser. The last update I've gotten is version 1.14.8.

Trying to install it on a fresh Edge browser from Microsoft Add-ons gives this error: 
"An error has occurred
The add-on could not be verified as the add-on manifest file is invalid."

**Comment by conceptualspace** [comment]
thanks for the report. unfortunately i don't have edge to test against, but maybe there was a trailing comma in the manifest file -- it is one of the things that gets modified between chrome/edge and firefox releases. i'll push the latest release today (v1.15.7) and see if that resolves the issue

nothing awkward about this validation message from MS.. :yum: 

![ms](https://user-images.githubusercontent.com/4175632/144684247-4c1e1a2c-1a7b-40fa-ad30-4ce223a9c3c4.png)

**Comment by conceptualspace** [comment]
@bb10 v1.15.7 is now available for edge, does that resolve the issue?

**Comment by bb10** [comment]
Yes, it works now. Thank you!
