### ISSUE TITLE
New version of plugin reversed the order of bookmarks in speed dial

### ISSUE THREAD

**Issue by o010b** [conceptualspace/yet-another-speed-dial#53]
I've already sorted them in the Firefox bookmarks to have it consistent over devices. Old order is top to bottom, worked fine. New version flips the order so that lowest bookmark in ff bookmarks folder shows up first in speed dial. Please revert to old sorting order. Thanks.

**Comment by conceptualspace** [comment]
thanks for the report. what sort order do you have in the YASD settings?

**Comment by o010b** [comment]
My mistake, I didn't realize there was a setting.
