### ISSUE TITLE
Image Placement

### ISSUE THREAD

**Issue by khbehrens** [conceptualspace/yet-another-speed-dial#59]
The images rearrange themselves when Firefox opens. I have to put them back the way I want them displayed. The placement does not stick between sessions. I believe this behavior started after the latest update to Speed Dial. Linux Firefox V 98.0.1, OS Ubuntu 20.04.

**Comment by conceptualspace** [comment]
Hmm. Can you compare how they're ordered in the bookmarks manager (Ctrl + Shift + O)? They should match.

Also what exact version of YASD? 2.1.8?

**Comment by khbehrens** [comment]
They match the order in the bookmarks manager. I reordered them after 
Firefox launch this morning. I'll check it when they get scrambled and 
update you with the results.
I am on YASD v2.1.8.

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   03/20/2022 08:37
Subject:        Re: [conceptualspace/yet-another-speed-dial] Image 
Placement (Issue #59)



Hmm. Can you compare how they're ordered in the bookmarks manager (Ctrl + 
Shift + O)? They should match.
Also what exact version of YASD? 2.1.8?
?
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by khbehrens** [comment]
I just checked Firefox on one of my other machines and they are scrambled 
but the bookmark manager has the correct order in the speed dial folder.
All of my machines are running the same Firefox software and OS version. 
Firefox syncs across all my machines.

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   03/20/2022 08:37
Subject:        Re: [conceptualspace/yet-another-speed-dial] Image 
Placement (Issue #59)



Hmm. Can you compare how they're ordered in the bookmarks manager (Ctrl + 
Shift + O)? They should match.
Also what exact version of YASD? 2.1.8?
?
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by conceptualspace** [comment]
Can you check the "Sort" setting in YASD and confirm it is the same on both devices?

**Comment by khbehrens** [comment]
Both sort options are the same "new dials last".

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   03/20/2022 15:27
Subject:        Re: [conceptualspace/yet-another-speed-dial] Image 
Placement (Issue #59)



Can you check the "Sort" setting in YASD and confirm it is the same on 
both devices?
?
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by khbehrens** [comment]
I checked the entries in the speed dial bookmarks and the order is the 
same as the scrambled display on the speed dial screen. The previous order 
I saw as correct must have been after a firefox sync happened.

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com

**Comment by khbehrens** [comment]
I finally figured out what caused the reordering and it was related to 
sync but it only happens when I sort the bookmarks with the auto-sort 
bookmarks extension. I removed the speed dial folder from the sorting in 
the config folders tab on every instance of firefox and that stopped the 
propagation of the reordered speed dials. 

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   03/23/2022 10:57
Subject:        Re: [conceptualspace/yet-another-speed-dial] Image 
Placement (Issue #59)



yes i think it must be related to the sync. so when they are all synced 
up, and you restart your browser, is everything as expected now? let me 
know if something else is going on
?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by khbehrens** [comment]
Sorry I haven't got back to you. I had some minor surgery and was off line 
for a while.
I have ascertained that in fact if another machine modified the order, it 
got propagated to the other speed dials on a sync. I believe they got 
rearranged when Firefox did a version upgrade, still looking into that 
possibility.
I suggest that there be a preference to lock the order, but it's not a big 
deal if this is not an option to code.

73 & Cheers,
Ken Behrens
HCL Domino/Notes Application Developer
MicroBlue Software, LLC 
KB0YLN
E-mail: ***@***.***
Web site:  http://www.MicroBlueSoftware.com



From:   "conceptualspace" ***@***.***>
To:     "conceptualspace/yet-another-speed-dial" 
***@***.***>
Cc:     "khbehrens" ***@***.***>, "Author" 
***@***.***>
Date:   03/23/2022 10:57
Subject:        Re: [conceptualspace/yet-another-speed-dial] Image 
Placement (Issue #59)



yes i think it must be related to the sync. so when they are all synced 
up, and you restart your browser, is everything as expected now? let me 
know if something else is going on
?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by conceptualspace** [comment]
thanks for the response ken and hope you are well! am closing for now as expected behavior but may revisit sync more thoroughly in the future
