### ISSUE TITLE
Icons mostly not working

### ISSUE THREAD

**Issue by SufyanDahalan** [conceptualspace/yet-another-speed-dial#75]
Icons are not detected correctly most of the time. Firefox shortcuts does however detect most icons correctly.
I saw that you use clearbit to search for logos and icons, i want to suggest using google.
p.s.: compare the result for sideprojectors on [google](https://www.google.com/s2/favicons?domain=https://secondfounder.com&sz=256) and [clearbit](https://logo.clearbit.com/https://secondfounder.com/?size=256), which falls back to a some kind of screenshot of the page.

**Comment by conceptualspace** [comment]
just to clarify, yasd will try to use an opengraph image before the favicon -- do they work as expected? 

and if you edit a dial and scroll through the images it found, is the right logo in there at all, or totally missing? if most of the sites are missing icons do you mind sharing some of the domains? thanks!

**Comment by conceptualspace** [comment]
so i just tried with secondfounder.com and indeed the default image yasd uses is the opengraph image from the page. if you edit the dial you'll see yasd has found 4 different images, with the logo you shared being the second option. you can just choose the one you want and no need to query google :smile:

**Comment by conceptualspace** [comment]
this does make me think that maybe it would be helpful to have a setting in yasd to prefer favicons or open graph images. generally the former are better for top level domains but the latter works better for more specific pages
