### ISSUE TITLE
[FR] option to disable thumbnails

### ISSUE THREAD

**Issue by mrx23dot** [conceptualspace/yet-another-speed-dial#77]
I found snapshots to be slow and unnecessary, please add an option to disable and only show solid colors+domain name or initials if too long, 

colors derived from hash on domain name, (similar as in stock Opera browser)

**Comment by conceptualspace** [comment]
serious question: if thumbnails are totally disabled do you still find YASD useful?

i do agree having more options for image capture is a good idea. will iterate on this over the next few releases. thanks!

**Comment by SerafDosSantos** [comment]
@mrx23dot true... faster.

I don't mind the "once" 2-3 seconds. I like images, but some media images lack "goodness".

The simple option to choose domain name per default as tile-view settings option would suffice to choose the view.
