### ISSUE TITLE
Can't See Import/Export Settings Feature.. Where is it?

### ISSUE THREAD

**Issue by geedogz** [conceptualspace/yet-another-speed-dial#78]
Hi.. I can't see the import or export of settings feature. Where is it?

**Comment by SerafDosSantos** [comment]
![Web capture_5-2-2023_9216_newtab](https://user-images.githubusercontent.com/3285430/216825029-c6d68d4f-e203-46f1-b0fa-20d9db374913.jpeg)

**Comment by conceptualspace** [comment]
closing this as resolved but please feel free to reopen if you still have an issue
