### ISSUE TITLE
Feature request: Importing from other addons

### ISSUE THREAD

**Issue by Mav3r1x** [conceptualspace/yet-another-speed-dial#8]
What makes it almost impossible to move to a different(better) speed dial addon is the data. I use speed dial 2 and have more than 500 dials in different groups.

It would be a nice idea to import data from other addons.

**Comment by conceptualspace** [comment]
good idea, i'll check it out.

FYI in our case the speed dials are fundamentally just bookmarks inside the 'speed dial' folder. so they can be synced/exported/imported along with the rest of you browser's bookmarks. that wouldn't include the thumbnails (although they would be automatically regenerated on import) or sorting order though, so it's probably still worth adding an export function as well.

**Comment by conceptualspace** [comment]
merging with #31
