### ISSUE TITLE
Amazon UK thumbnail

### ISSUE THREAD

**Issue by wards999** [conceptualspace/yet-another-speed-dial#80]
When I add a link to amazon.co.uk I get

![am](https://user-images.githubusercontent.com/83018031/219875218-8fe01782-a3f8-44ed-93dc-a69f6f021176.png)

I know I can use my own saved image - but for a major site like Amazon wouldn't it get a better logo?

**Comment by conceptualspace** [comment]
thanks for reporting this! yes there is specific logic in yasd for amazon, i'll update it :)

**Comment by wards999** [comment]
thanks 👍
