### ISSUE TITLE
YASD opens blank - SD's are in bookmarks manager

### ISSUE THREAD

**Issue by gbeyer3** [conceptualspace/yet-another-speed-dial#87]
My new browser windows and tabs have started  opening with no speed dialers.  The YASD interface is there with clock and setting widget upper right, and folder upper left, just no dialers.  I have cycled the browser, and the plugin (disable/enable) multiple times.   Looking in the Bookmarks manager, I find all of my dialers and folders under Other Bookmarks / Speed dial.   So. what's gone wrong?  How can I fix or troubleshoot this?

FIrefox 113.0.2 on LinuxMint   In settings, both Home, new Windows and New Tabs are set to "yet another speed dial" 

Thanks.

**Comment by klausph** [comment]
Thank You for this advise. my bookmarks from YASD were in an other folder, and YAD was empty. solution was easy. thank You. Klaus
